name: hello

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run:
          echo "Hello World!"
      - name: List Directory
        run:
          ls
      - name: Get Date
        run:
          date
